### ISSUE TITLE
Doesn't work on my System

### ISSUE THREAD

**Issue by rittamdebnath** [HugoGiraudel/sass-guidelines#341]
npm ERR! Linux 4.2.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v5.7.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! @ postbuild: `_bin/testbuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ postbuild script '_bin/testbuild'.

**Comment by HugoGiraudel** [comment]
It should now be fixed. Try again?

**Comment by rittamdebnath** [comment]
Still not working . when i do `npm start` it gets stuck in between showing some error . Below are some of the Screenshot that i would like to share with you . 

![pic -0](https://cloud.githubusercontent.com/assets/7520259/13461799/bd36b45e-e0a9-11e5-82a5-c85a59e80567.png)
![pic 1](https://cloud.githubusercontent.com/assets/7520259/13461797/bd30ebb4-e0a9-11e5-98f3-3f9999d42da2.png)
![pic -2](https://cloud.githubusercontent.com/assets/7520259/13461800/bd387f82-e0a9-11e5-8e55-ecff892c33c6.png)
![pic -3](https://cloud.githubusercontent.com/assets/7520259/13461798/bd3448ea-e0a9-11e5-8568-782a4da4a623.png)

**Comment by HugoGiraudel** [comment]
Alright, give me a few minutes and I’ll investigate. Thanks for reporting by the way. :)

**Comment by HugoGiraudel** [comment]
Okay, I cannot reproduce it on my machine. Your current problem is that for some reason `_site/assets/css/main.css` is not being generated, which is super odd. 

Could you please try this:

```
rm -rf node_modules
npm install
bundle install
npm start
```

… and tell me if it fails in `_bin/buildtest` again?

**Comment by HugoGiraudel** [comment]
Found the problem. Should be fixed with: https://github.com/HugoGiraudel/sass-guidelines/commit/851fabe72f2939125ce2a0e8ca3d376998636b0f.
